function RTW_SidParentMap() {
    this.sidParentMap = new Array();
    this.sidParentMap["ForceController:40"] = "ForceController";
    this.sidParentMap["ForceController:45"] = "ForceController";
    this.sidParentMap["ForceController:70"] = "ForceController";
    this.sidParentMap["ForceController:16"] = "ForceController";
    this.sidParentMap["ForceController:4"] = "ForceController";
    this.sidParentMap["ForceController:54"] = "ForceController";
    this.sidParentMap["ForceController:71"] = "ForceController";
    this.sidParentMap["ForceController:55"] = "ForceController";
    this.sidParentMap["ForceController:47"] = "ForceController";
    this.sidParentMap["ForceController:17"] = "ForceController";
    this.sidParentMap["ForceController:46"] = "ForceController";
    this.sidParentMap["ForceController:42"] = "ForceController";
    this.sidParentMap["ForceController:4:1"] = "ForceController:4";
    this.sidParentMap["ForceController:4:1687"] = "ForceController:4";
    this.sidParentMap["ForceController:4:1688"] = "ForceController:4";
    this.sidParentMap["ForceController:4:1686"] = "ForceController:4";
    this.sidParentMap["ForceController:4:1685"] = "ForceController:4";
    this.sidParentMap["ForceController:4:10"] = "ForceController:4";
    this.sidParentMap["ForceController:72"] = "ForceController:71";
    this.sidParentMap["ForceController:66"] = "ForceController:71";
    this.sidParentMap["ForceController:60"] = "ForceController:71";
    this.sidParentMap["ForceController:61"] = "ForceController:71";
    this.sidParentMap["ForceController:62"] = "ForceController:71";
    this.sidParentMap["ForceController:63"] = "ForceController:71";
    this.sidParentMap["ForceController:64"] = "ForceController:71";
    this.sidParentMap["ForceController:65"] = "ForceController:71";
    this.sidParentMap["ForceController:67"] = "ForceController:71";
    this.sidParentMap["ForceController:73"] = "ForceController:71";
    this.getParentSid = function(sid) { return this.sidParentMap[sid];}
}
    RTW_SidParentMap.instance = new RTW_SidParentMap();
